services:
  api:
    build: ./ruby_api
    environment:
    - REDIS_URL=redis://redis:6379
    - USER_AMOUNT=500
    image: linkextractor-api:step5-python
    ports:
    - 5000:5000
  redis:
    image: redis
  web:
    build: ./www
    environment:
    - API_ENDPOINT=http://api:5000/api/
    image: linkextractor-web:step5-php
    ports:
    - 80:80
version: '3'
